
# ---------------------------------------------------
# This file is autogenerated by git-version-builder.
# DO NOT MODIFY!
# ---------------------------------------------------

VERSION_STRING = "v0.9-0-gf576"
TAG_NAME = "v0.9"
COMMITS_SINCE_TAG = 0
GIT_COMMIT_ID = "f576"
