
# ---------------------------------------------------
# This file is autogenerated by git-version-builder.
# DO NOT MODIFY!
# ---------------------------------------------------

VERSION_STRING = "heads/develop-0-gc107328"
TAG_NAME = "heads/develop"
COMMITS_SINCE_TAG = 0
GIT_COMMIT_ID = "c107328"
