
# ---------------------------------------------------
# This file is autogenerated by git-version-builder.
# DO NOT MODIFY!
# ---------------------------------------------------

VERSION_STRING = "dummy"
TAG_NAME = "dummy"
COMMITS_SINCE_TAG = 0
GIT_COMMIT_ID = "dummy"
